# Generated by Django 4.2.7 on 2023-12-03 17:08

import helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "gid",
                    models.CharField(
                        default=helpers.generate_id, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("template", models.JSONField()),
                ("active", models.BooleanField(default=False)),
                ("published_entries_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "collections",
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "gid",
                    models.CharField(
                        default=helpers.generate_id, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.BigIntegerField()),
                ("collection_id", models.BigIntegerField()),
                ("content", models.JSONField(default=dict)),
                ("template", models.JSONField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Init"),
                            (10, "Draft"),
                            (20, "Published"),
                            (30, "Inactive"),
                        ],
                        default=10,
                    ),
                ),
                ("published_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "entries",
            },
        ),
    ]
